#index:
#    path: /
#    controller: App\Controller\DefaultController::index

todos_overdue:
  path: api/todos/overdue/details
  methods: 'GET'
  defaults:
    _controller: App\Controller\TodoController::todosOverdue
    _api_resource_class: App\Entity\Todo
    _api_collection_operation_name: todos_overdue

todos_today:
  path: api/todos/today/details/{date}
  methods: 'GET'
  defaults:
    _controller: App\Controller\TodoController::todosToday
    _api_resource_class: App\Entity\Todo
    _api_collection_operation_name: todos_today

todos_next:
  path: api/todos/next/details
  methods: 'GET'
  defaults:
    _controller: App\Controller\TodoController::todosNext
    _api_resource_class: App\Entity\Todo
    _api_collection_operation_name: todos_next