#index:
#    path: /
#    controller: App\Controller\DefaultController::index

todos_overdue:
  path: api/todos/overdue/details
  methods: 'GET'
  defaults:
    _controller: App\Controller\TodoController::todosOverdue
    _api_resource_class: App\Entity\Todo
    _api_collection_operation_name: todos_overdue